services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - APP_NAME=${APP_NAME}
      - APP_DEBUG=${APP_DEBUG}
      - APP_RELOAD=${APP_RELOAD}
      - APP_CONTAINER_ADDRESS=${APP_CONTAINER_ADDRESS}
      - APP_CONTAINER_PORT=${APP_CONTAINER_PORT}
      - BACKEND_CONTAINER_ADDRESS=${BACKEND_CONTAINER_ADDRESS}
      - APP_ENABLE_INTERACTIONS=${APP_ENABLE_INTERACTIONS}
      - APP_ENABLE_LEARNERS=${APP_ENABLE_LEARNERS}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${CONST_POSTGRESQL_DEFAULT_PORT}/${POSTGRES_DB}
      - AUTOCHECKER_API_URL=${AUTOCHECKER_API_URL}
      - AUTOCHECKER_API_LOGIN=${AUTOCHECKER_API_LOGIN}
      - AUTOCHECKER_API_PASSWORD=${AUTOCHECKER_API_PASSWORD}
      - LMS_API_KEY=${LMS_API_KEY}
    ports:
      - "${BACKEND_HOST_PORT}:${BACKEND_CONTAINER_PORT}"
    depends_on:
      - postgres
    networks:
      - default

  caddy:
    image: caddy:2-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "${CADDY_HOST_PORT}:${CADDY_CONTAINER_PORT}"
    depends_on:
      - backend
    networks:
      - default

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_HOST_PORT}:${CONST_POSTGRESQL_DEFAULT_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_HOST_PORT}:${CONST_PGADMIN_CONTAINER_PORT}"
    depends_on:
      - postgres
    networks:
      - default

  bot:
    build:
      context: .
      dockerfile: bot/Dockerfile
    container_name: se-toolkit-lab-7-bot-1
    env_file:
      - .env.bot.secret
    depends_on:
      - backend
    networks:
      - default
    restart: unless-stopped

networks:
  default:
    name: se-toolkit-lab-7_default

volumes:
  postgres_data:
